language: node_js
sudo: false

node_js:
  - "8"
  - "10"
  - "12"

matrix:
  include:
    - name: "Linux - Node 12"
      os: linux
      node_js: "12"
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
    - name: "OS X - Node 12"
      os: osx
      node_js: "12"
      osx_image: xcode11
      compiler: clang
      env:
        - CXX=g++
        - CC=gcc
before_deploy:
  - npm run build
  - $(npm bin)/prebuild -r node -t 12.18.1
deploy:
  provider: releases
  api_key:
    secure: "dp4IfUt7ex3ejmJhRlkcu+RbINLxMU/Xu2Aa0TShX2YYPuNkdSH2+kLSP7BAEUyAxVrxdBEt6LOoHgGaN6ssJnlc7FKkAQsik10emX+gTW/wDtFA2wAeOIh7iXXWMmdnsttTxh5FyXwjsIax0MbVN1bvNjM3AviK4i5jLJuXueQ="
  file: prebuilds/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: gemini-testing/png-img
    tags: true
    node_js: "12"
